import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ConvexClientProvider } from "./ConvexClientProvider";
import Sidebar from "@/components/Sidebar";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/toaster";
import MobileMenu from "@/components/MobileMenu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Stock management system",
  description: "Generated by emino.dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-full w-full scroll-smooth relative`}
      >
        <div className="w-fit h-fit bg-white left-3 top-5 shadow-sm shadow-black/20 px-1 lg:hidden fixed z-30">
          <MobileMenu />
        </div>
        <div className="md:flex flex-col min-h-screen px-2 py-7 w-fit bg-gray-50 dark:text-gray-800 hidden">
          <Sidebar />
        </div>
        <div className="flex items-start mt-8 flex-col justify-center w-full  px-3 md:px-6  min-h-screen ">
          <ConvexClientProvider>
            {" "}
            <NextTopLoader showSpinner={false} />
            <div className="flex h-full w-full ">
              {children}
              <Toaster />
            </div>
          </ConvexClientProvider>
        </div>
      </body>
    </html>
  );
}
